"""initial migration

Revision ID: 305a67d8d629
Revises: 
Create Date: 2021-10-14 20:53:36.543622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305a67d8d629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('client_id', name=op.f('uq_user_client_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
